# Generated by Django 6.1.1 on 2026-09-18 23:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'উপস্থিত'), ('ABSENT', 'অনুপস্থিত'), ('LATE', 'বিলম্বে উপস্থিত')], default='PRESENT', max_length=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SAT', 'শনিবার'), ('SUN', 'রবিবার'), ('MON', 'সোমবার'), ('TUE', 'মঙ্গলবার'), ('WED', 'বুধবার'), ('THU', 'বৃহস্পতিবার'), ('FRI', 'শুক্রবার')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('WEEKLY', 'সাপ্তাহিক পরীক্ষা'), ('MONTHLY', 'মাসিক পরীক্ষা'), ('MODEL', 'মডেল টেস্ট'), ('FINAL', 'বার্ষিক/চূড়ান্ত পরীক্ষা')], default='WEEKLY', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-exam__date'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')])),
                ('year', models.PositiveIntegerField(default=2026)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PAID', 'পরিশোধিত'), ('DUE', 'বকেয়া'), ('PARTIAL', 'আংশিক পরিশোধিত')], default='DUE', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pinned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='যেমনঃ ষষ্ঠ শ্রেণি, SSC ব্যাচ', max_length=100, unique=True)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='তালিকায় ক্রম নির্ধারণের জন্য')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
